---
  - name: Create database for keystone
    mysql_db: login_user=root login_password={{ mysql_root_password  }} name=keystone state=present
  - name: Create keystone user and grant privileges to keystone database.
    mysql_user: login_user=root login_password={{ mysql_root_password  }} name=keystone password={{ keystone_dbpass }} priv=*.*:ALL state=present host={{ item }}
    with_items:
     - "{{ controller_eth1 }}"
     - 127.0.0.1
     - localhost
     - ::1
  - name: disable keystone auto start service
    lineinfile: dest=/etc/init/keystone.override line=manual create=yes
  - name: Install keystone apache2 libapache2-mod-wsgi in controller node
    apt: name={{ item }} state=present force=yes
    with_items:
     - keystone
     - apache2
     - libapache2-mod-wsgi
  - name: update /etc/keystone/keystone.conf
    ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=admin_token
              value={{ openssl_rand }}
              backup=yes

  - name: update /etc/keystone/keystone.conf
    ini_file: dest=/etc/keystone/keystone.conf
              section=database
              option=connection
              value=mysql+pymysql://keystone:{{ keystone_dbpass }}@{{ controller_eth1 }}/keystone
              backup=yes

  - name: update /etc/keystone/keystone.conf
    ini_file: dest=/etc/keystone/keystone.conf
              section=token
              option=provider
              value=fernet
              backup=yes
 
  - name: Populate the Identity service database in controller node
    shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  - name: Initialize Fernet keys
    shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

  - name: updaete /etc/apache2/apache2.conf
#    lineinfile: dest=/etc/apache2/apache2.conf regexp="^ServerName" line= "ServerName {{ controller_eth1 }}"
    lineinfile: dest=/etc/apache2/apache2.conf line= "ServerName {{ controller_eth1 }}"
  - name: update /etc/apache2/sites-available/wsgi-keystone.conf
    template: src=wsgi-keystone.conf.j2 dest=/etc/apache2/sites-available/wsgi-keystone.conf
  - name: Enable the Identity service virtual hosts
    file: src=/etc/apache2/sites-available/wsgi-keystone.conf dest=/etc/apache2/sites-enabled/wsgi-keystone.conf state=link
  - name: Restart Apache2
    service: name=apache2 state=restarted
  - name: Remove /var/lib/keystone/keystone.db
    file: path=/var/lib/keystone/keystone.db state=absent
  - name: Create admin-openrc.sh file
    template: src=admin-openrc.sh.j2 dest=/root/admin-openrc.sh
  - name: Create demo-openrc.sh file
    template: src=demo-openrc.sh.j2 dest=/root/demo-openrc.sh
  - name: Configure all tenants, users, roles, services and endpoints
    template: src=keystone-all.sh.j2 dest=/var/tmp/keystone-all.sh
  - command: bash /var/tmp/keystone-all.sh
